env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
overrides:
  - files:
    - webpack.config.js
    env:
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
