env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  'import/order':
    - warn
    - alphabetize:
        order: asc
overrides:
  - files:
      - webpack.config.js
    env:
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
